name: Ouverture du Restaurant

# Le workflow se d√©clenche √† chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  ouverture:
    # D√©finir l'environnement d'ex√©cution
    runs-on: ubuntu-latest
    
    steps:
      # √âtape simple qui annonce l'ouverture
      - name: Annoncer l'ouverture
        run: echo "üçΩÔ∏è Le restaurant est ouvert !"