name: Tests Addition

on:
  push:
    branches:
      - main

jobs:
   tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    name: Node.js ${{ matrix.node-version }} Tests
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3

      - name: Installer Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer les dépendances
        run: npm install

      - name: linter
        run : npm install --save-dev eslint @eslint/js globals

      - name: test lint
        run: npm run lint

      - name: test addition
        run: npm test